version: '2.1'

services:

    client:
        volumes:
            - client-sync:/opt/app:nocopy

    server:
        volumes:
            - server-sync:/opt/app:nocopy

volumes:
    server-sync:
        external: true
    client-sync:
        external: true
